version: '3.4'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8083:80
      - 8443:443
    environment:
      - PUID=1027
      - PGID=100
      - DB_CONNECTION=sqlite
    volumes:
      - /volume1/docker/speedtest-tracker/config:/config
    # - /path/to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
